/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Vehicle,
  Driver,
  Trip,
  MaintenanceLog,
  FuelLog,
  Expense,
  TeamMember,
  RolePermissionsMap,
  SystemNotification,
} from './types';

// Default Role Permissions Matrix
export const initialRolePermissions: RolePermissionsMap = {
  admin: {
    dashboard: ['view', 'create', 'edit', 'delete'],
    vehicles: ['view', 'create', 'edit', 'delete'],
    drivers: ['view', 'create', 'edit', 'delete'],
    trips: ['view', 'create', 'edit', 'delete'],
    maintenance: ['view', 'create', 'edit', 'delete'],
    fuel: ['view', 'create', 'edit', 'delete'],
    expenses: ['view', 'create', 'edit', 'delete'],
    reports: ['view', 'create', 'edit', 'delete'],
    rbac: ['view', 'create', 'edit', 'delete'],
    settings: ['view', 'create', 'edit', 'delete'],
  },
  dispatcher: {
    dashboard: ['view'],
    vehicles: ['view', 'edit'],
    drivers: ['view', 'create', 'edit'],
    trips: ['view', 'create', 'edit', 'delete'],
    maintenance: ['view'],
    fuel: ['view', 'create'],
    expenses: ['view'],
    reports: ['view'],
    rbac: ['view'],
    settings: ['view'],
  },
  maintenance: {
    dashboard: ['view'],
    vehicles: ['view', 'edit'],
    drivers: ['view'],
    trips: ['view'],
    maintenance: ['view', 'create', 'edit', 'delete'],
    fuel: ['view', 'create', 'edit'],
    expenses: ['view', 'create', 'edit'],
    reports: ['view'],
    rbac: ['view'],
    settings: ['view'],
  },
  viewer: {
    dashboard: ['view'],
    vehicles: ['view'],
    drivers: ['view'],
    trips: ['view'],
    maintenance: ['view'],
    fuel: ['view'],
    expenses: ['view'],
    reports: ['view'],
    rbac: [],
    settings: ['view'],
  },
};

// Initial Vehicles
export const initialVehicles: Vehicle[] = [
  {
    id: 'v-1',
    code: 'BUS-101',
    name: 'Metro Transit Bus 101',
    type: 'Bus',
    status: 'Active',
    mileage: 142350,
    fuelType: 'Diesel',
    fuelLevel: 84,
    licensePlate: 'TX-Transit-810A',
    year: 2019,
    lastServiceDate: '2026-06-15',
    registrationNumber: 'REG-TX-98711',
    maxLoadCapacity: 15000,
    acquisitionCost: 285000,
  },
  {
    id: 'v-2',
    code: 'TRK-204',
    name: 'Freightliner M2 Heavy Cargo',
    type: 'Heavy Truck',
    status: 'Active',
    mileage: 89410,
    fuelType: 'CNG',
    fuelLevel: 62,
    licensePlate: 'CA-Freight-049F',
    year: 2021,
    lastServiceDate: '2026-05-20',
    registrationNumber: 'REG-CA-44512',
    maxLoadCapacity: 33000,
    acquisitionCost: 145000,
  },
  {
    id: 'v-3',
    code: 'VAN-302',
    name: 'Ford Transit Delivery 302',
    type: 'Delivery Van',
    status: 'Maintenance',
    mileage: 45120,
    fuelType: 'Electric',
    fuelLevel: 12,
    licensePlate: 'NY-Cargo-901D',
    year: 2022,
    lastServiceDate: '2026-07-10',
    registrationNumber: 'REG-NY-80129',
    maxLoadCapacity: 4500,
    acquisitionCost: 55000,
  },
  {
    id: 'v-4',
    code: 'SHT-405',
    name: 'Mercedes-Benz Sprinter Shuttle',
    type: 'Shuttle',
    status: 'Active',
    mileage: 67340,
    fuelType: 'Hybrid',
    fuelLevel: 91,
    licensePlate: 'FL-Shuttle-405S',
    year: 2020,
    lastServiceDate: '2026-06-28',
    registrationNumber: 'REG-FL-30122',
    maxLoadCapacity: 8000,
    acquisitionCost: 75000,
  },
  {
    id: 'v-5',
    code: 'BUS-102',
    name: 'Electric articulated Bus 102',
    type: 'Bus',
    status: 'Active',
    mileage: 23150,
    fuelType: 'Electric',
    fuelLevel: 78,
    licensePlate: 'TX-Electric-202B',
    year: 2023,
    lastServiceDate: '2026-07-01',
    registrationNumber: 'REG-TX-10492',
    maxLoadCapacity: 16000,
    acquisitionCost: 340000,
  },
  {
    id: 'v-6',
    code: 'TRK-208',
    name: 'Peterbilt 579 Long Haul',
    type: 'Heavy Truck',
    status: 'Out of Service',
    mileage: 198450,
    fuelType: 'Diesel',
    fuelLevel: 5,
    licensePlate: 'NV-Truck-008T',
    year: 2018,
    lastServiceDate: '2026-04-12',
    registrationNumber: 'REG-NV-00811',
    maxLoadCapacity: 40000,
    acquisitionCost: 165000,
  },
];

// Initial Drivers
export const initialDrivers: Driver[] = [
  {
    id: 'd-1',
    name: 'Marcus Vance',
    email: 'marcus.vance@transitops.com',
    phone: '+1 (555) 234-5678',
    licenseNumber: 'CDL-TX-892301',
    licenseCategory: 'CDL Class A',
    licenseType: 'CDL Class A',
    licenseExpiryDate: '2028-11-20',
    contactNumber: '+1 (555) 234-5678',
    safetyScore: 96,
    status: 'Available',
    rating: 4.8,
    assignedVehicleId: 'v-1',
    joinedDate: '2021-03-12',
    createdAt: '2021-03-12T08:00:00Z',
    updatedAt: '2026-07-10T15:30:00Z',
  },
  {
    id: 'd-2',
    name: 'Sarah Connor',
    email: 'sarah.connor@transitops.com',
    phone: '+1 (555) 345-6789',
    licenseNumber: 'CDL-CA-443219',
    licenseCategory: 'CDL Class A',
    licenseType: 'CDL Class A',
    licenseExpiryDate: '2027-04-15',
    contactNumber: '+1 (555) 345-6789',
    safetyScore: 98,
    status: 'On Trip',
    rating: 4.9,
    assignedVehicleId: 'v-2',
    joinedDate: '2022-08-19',
    createdAt: '2022-08-19T09:00:00Z',
    updatedAt: '2026-07-11T10:15:00Z',
  },
  {
    id: 'd-3',
    name: 'Elena Rostova',
    email: 'elena.rostova@transitops.com',
    phone: '+1 (555) 456-7890',
    licenseNumber: 'CDL-NY-110294',
    licenseCategory: 'CDL Class B',
    licenseType: 'CDL Class B',
    licenseExpiryDate: '2028-02-28',
    contactNumber: '+1 (555) 456-7890',
    safetyScore: 94,
    status: 'Available',
    rating: 4.7,
    assignedVehicleId: null,
    joinedDate: '2023-01-15',
    createdAt: '2023-01-15T11:00:00Z',
    updatedAt: '2026-07-09T14:20:00Z',
  },
  {
    id: 'd-4',
    name: 'David Kim',
    email: 'david.kim@transitops.com',
    phone: '+1 (555) 567-8901',
    licenseNumber: 'DL-FL-772849',
    licenseCategory: 'Standard',
    licenseType: 'Standard',
    licenseExpiryDate: '2029-06-30',
    contactNumber: '+1 (555) 567-8901',
    safetyScore: 92,
    status: 'On Trip',
    rating: 4.6,
    assignedVehicleId: 'v-4',
    joinedDate: '2024-05-10',
    createdAt: '2024-05-10T14:30:00Z',
    updatedAt: '2026-07-11T09:00:00Z',
  },
  {
    id: 'd-5',
    name: 'Clara Oswald',
    email: 'clara.oswald@transitops.com',
    phone: '+1 (555) 678-9012',
    licenseNumber: 'CDL-TX-556102',
    licenseCategory: 'CDL Class B',
    licenseType: 'CDL Class B',
    licenseExpiryDate: '2027-10-05',
    contactNumber: '+1 (555) 678-9012',
    safetyScore: 90,
    status: 'Off Duty',
    rating: 4.5,
    assignedVehicleId: null,
    joinedDate: '2023-11-01',
    createdAt: '2023-11-01T10:00:00Z',
    updatedAt: '2026-07-05T12:00:00Z',
  },
  {
    id: 'd-6',
    name: 'Robert Jenkins',
    email: 'robert.jenkins@transitops.com',
    phone: '+1 (555) 789-0123',
    licenseNumber: 'CDL-NV-902183',
    licenseCategory: 'CDL Class A',
    licenseType: 'CDL Class A',
    licenseExpiryDate: '2026-09-12',
    contactNumber: '+1 (555) 789-0123',
    safetyScore: 78,
    status: 'Suspended',
    rating: 3.9,
    assignedVehicleId: null,
    joinedDate: '2020-02-28',
    createdAt: '2020-02-28T09:00:00Z',
    updatedAt: '2026-06-20T16:00:00Z',
  },
];

// Initial Trips
export const initialTrips: Trip[] = [
  {
    id: 't-1',
    tripNumber: 'TRIP-4011',
    vehicleId: 'v-1',
    driverId: 'd-1',
    routeName: 'Route 12B - Downtown Express',
    origin: 'Central Transit Hub',
    destination: 'North Airport Terminal',
    scheduledDeparture: '2026-07-11T08:00:00',
    actualDeparture: '2026-07-11T08:02:00',
    scheduledArrival: '2026-07-11T09:15:00',
    status: 'Completed',
    passengers: 42,
    stopsCount: 8,
  },
  {
    id: 't-2',
    tripNumber: 'TRIP-4012',
    vehicleId: 'v-2',
    driverId: 'd-2',
    routeName: 'Cargo Shuttle - Industrial Corridor',
    origin: 'Eastside Manufacturing Depot',
    destination: 'West Port Port Authority',
    scheduledDeparture: '2026-07-11T20:30:00',
    actualDeparture: '2026-07-11T20:45:00',
    scheduledArrival: '2026-07-12T02:00:00',
    status: 'En Route',
    passengers: 0,
    stopsCount: 2,
  },
  {
    id: 't-3',
    tripNumber: 'TRIP-4013',
    vehicleId: 'v-4',
    driverId: 'd-4',
    routeName: 'Tech Campus Commuter Route C',
    origin: 'Suburban Commuter Station',
    destination: 'HQ Corporate Park',
    scheduledDeparture: '2026-07-11T21:40:00',
    scheduledArrival: '2026-07-11T22:30:00',
    status: 'En Route',
    passengers: 12,
    stopsCount: 4,
  },
  {
    id: 't-4',
    tripNumber: 'TRIP-4014',
    vehicleId: 'v-5',
    driverId: 'd-3',
    routeName: 'Late Night Loop Route 01',
    origin: 'Downtown Center Terminal',
    destination: 'University Heights Depot',
    scheduledDeparture: '2026-07-11T23:15:00',
    scheduledArrival: '2026-07-12T00:30:00',
    status: 'Scheduled',
    passengers: 0,
    stopsCount: 15,
  },
  {
    id: 't-5',
    tripNumber: 'TRIP-4015',
    vehicleId: 'v-1',
    driverId: 'd-1',
    routeName: 'Route 12B - Downtown Return',
    origin: 'North Airport Terminal',
    destination: 'Central Transit Hub',
    scheduledDeparture: '2026-07-11T18:00:00',
    actualDeparture: '2026-07-11T18:15:00',
    scheduledArrival: '2026-07-11T19:15:00',
    status: 'Completed',
    passengers: 28,
    stopsCount: 8,
  },
];

// Initial Maintenance Logs
export const initialMaintenanceLogs: MaintenanceLog[] = [
  {
    id: 'm-1',
    vehicleId: 'v-3',
    serviceType: 'Brake Replacement',
    description: 'Rear brake pad wear found during routine inspection. Replacing pads and resurfacing rotors.',
    cost: 450,
    date: '2026-07-10',
    status: 'In Progress',
    technicianName: 'Sandro Ramirez',
    priority: 'High',
  },
  {
    id: 'm-2',
    vehicleId: 'v-1',
    serviceType: 'Oil Change',
    description: 'Routine 10k mile synthetic oil change and fuel filter check.',
    cost: 180,
    date: '2026-06-15',
    status: 'Completed',
    technicianName: 'Sandro Ramirez',
    priority: 'Low',
  },
  {
    id: 'm-3',
    vehicleId: 'v-6',
    serviceType: 'Engine Repair',
    description: 'Transmission slipping and cooling system leaking radiator fluid. Undergoing comprehensive diagnostics.',
    cost: 3200,
    date: '2026-07-08',
    status: 'Scheduled',
    technicianName: 'Alex Mercer',
    priority: 'Critical',
  },
  {
    id: 'm-4',
    vehicleId: 'v-4',
    serviceType: 'Tire Rotation',
    description: 'All-season tire rotation and balance, pressure checked and aligned.',
    cost: 120,
    date: '2026-06-28',
    status: 'Completed',
    technicianName: 'Elena Rostova',
    priority: 'Low',
  },
];

// Initial Fuel Logs
export const initialFuelLogs: FuelLog[] = [
  {
    id: 'f-1',
    vehicleId: 'v-1',
    driverId: 'd-1',
    date: '2026-07-10',
    gallons: 45.2,
    cost: 171.76,
    odometerReading: 142100,
    stationName: 'Chevron Station #402',
  },
  {
    id: 'f-2',
    vehicleId: 'v-2',
    driverId: 'd-2',
    date: '2026-07-09',
    gallons: 62.1,
    cost: 211.14,
    odometerReading: 89120,
    stationName: 'Pilot Travel Center #11',
  },
  {
    id: 'f-3',
    vehicleId: 'v-4',
    driverId: 'd-4',
    date: '2026-07-08',
    gallons: 12.8,
    cost: 51.20,
    odometerReading: 67210,
    stationName: 'Shell Express North',
  },
  {
    id: 'f-4',
    vehicleId: 'v-1',
    driverId: 'd-1',
    date: '2026-07-05',
    gallons: 48.0,
    cost: 187.20,
    odometerReading: 141600,
    stationName: 'Chevron Station #402',
  },
];

// Initial Expenses
export const initialExpenses: Expense[] = [
  {
    id: 'e-1',
    category: 'Fuel',
    description: 'Refueling log for Metro Transit Bus 101',
    amount: 171.76,
    date: '2026-07-10',
    referenceId: 'f-1',
  },
  {
    id: 'e-2',
    category: 'Maintenance',
    description: 'Service Log #m-1 - Brake replacement for Ford Transit 302',
    amount: 450.00,
    date: '2026-07-10',
    referenceId: 'm-1',
  },
  {
    id: 'e-3',
    category: 'Tolls',
    description: 'Weekly automated toll pass charges (E-ZPass Central)',
    amount: 320.50,
    date: '2026-07-08',
  },
  {
    id: 'e-4',
    category: 'Salaries',
    description: 'Bi-weekly payroll for drivers & logistics operators',
    amount: 14500.00,
    date: '2026-07-01',
  },
  {
    id: 'e-5',
    category: 'Insurance',
    description: 'Commercial fleet premium monthly installment',
    amount: 2450.00,
    date: '2026-07-01',
  },
];

// System Team Members
export const initialTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Administrator Chief',
    email: 'admin@transitops.com',
    role: 'admin',
    status: 'Active',
    avatarColor: 'bg-emerald-600',
    joinedDate: '2024-01-10',
  },
  {
    id: 'tm-2',
    name: 'Dispatcher Jones',
    email: 'dispatch.jones@transitops.com',
    role: 'dispatcher',
    status: 'Active',
    avatarColor: 'bg-indigo-600',
    joinedDate: '2024-03-15',
  },
  {
    id: 'tm-3',
    name: 'Sandro Ramirez (Maint)',
    email: 'sandro.maint@transitops.com',
    role: 'maintenance',
    status: 'Active',
    avatarColor: 'bg-amber-600',
    joinedDate: '2024-02-20',
  },
  {
    id: 'tm-4',
    name: 'Jane Spector (Guest)',
    email: 'jane.spector@transitops.com',
    role: 'viewer',
    status: 'Active',
    avatarColor: 'bg-slate-600',
    joinedDate: '2025-05-11',
  },
];

// Default Notifications
export const initialNotifications: SystemNotification[] = [
  {
    id: 'n-1',
    title: 'Critical Maintenance Alert',
    message: 'Peterbilt Heavy Truck (TRK-208) fuel level is at 5% and is flagged Out of Service.',
    timestamp: '2026-07-11T21:10:00',
    type: 'danger',
    read: false,
  },
  {
    id: 'n-2',
    title: 'Service Completed',
    message: 'Routine Inspection completed on Articulated Bus 102 by technician Sandro Ramirez.',
    timestamp: '2026-07-11T18:45:00',
    type: 'success',
    read: false,
  },
  {
    id: 'n-3',
    title: 'Delayed Route',
    message: 'Cargo Shuttle - Industrial Corridor (TRIP-4012) is experiencing a 15-minute delay due to traffic.',
    timestamp: '2026-07-11T17:30:00',
    type: 'warning',
    read: true,
  },
];
